package eOlympics.ui;


import eOlympics.Config;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrameEstudiante.java
 *
 * Created on 08-Mar-2012, 21:16:21
 */

/**
 *
 * @author Lourdes
 */
public class JFrameEstudiante extends javax.swing.JFrame {

    /** Creates new form JFrameEstudiante */
    public JFrameEstudiante() {
        initComponents();
        this.setSize(700, 500);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCentral = new javax.swing.JPanel();
        panelInscripciones1 = new eOlympics.ui.PanelInscripciones();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mnuVer = new javax.swing.JMenu();
        jmnuAyuda = new javax.swing.JMenu();
        mnuEdicion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("eOlympics - Estudiante");

        jPanelCentral.setName("jPanelCentral"); // NOI18N
        jPanelCentral.setLayout(new java.awt.BorderLayout());

        panelInscripciones1.setName("panelInscripciones1"); // NOI18N
        jPanelCentral.add(panelInscripciones1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelCentral, java.awt.BorderLayout.CENTER);

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        mnuArchivo.setText("Archivo");
        mnuArchivo.setName("mnuArchivo"); // NOI18N
        jMenuBar1.add(mnuArchivo);

        mnuVer.setText("Ver");
        mnuVer.setName("mnuVer"); // NOI18N
        jMenuBar1.add(mnuVer);

        jmnuAyuda.setText("Ayuda");
        jmnuAyuda.setName("jmnuAyuda"); // NOI18N
        jMenuBar1.add(jmnuAyuda);

        mnuEdicion.setText("Edición");
        mnuEdicion.setName("mnuEdicion"); // NOI18N
        jMenuBar1.add(mnuEdicion);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        Config.LF_windows();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 new JFrameEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanelCentral;
    private javax.swing.JMenu jmnuAyuda;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenu mnuEdicion;
    private javax.swing.JMenu mnuVer;
    private eOlympics.ui.PanelInscripciones panelInscripciones1;
    // End of variables declaration//GEN-END:variables

}
