/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelPruebasRealizar.java
 *
 * Created on 17-Mar-2012, 20:27:01
 */

package eOlympics.ui;

/**
 *
 * @author Lourdes
 */
public class PanelPruebasRealizar extends javax.swing.JPanel {

    /** Creates new form PanelPruebasRealizar */
    public PanelPruebasRealizar() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPruebas = new javax.swing.JPanel();
        labelListado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPruebasARealizar1 = new ejemplos.TablaPruebasARealizar();
        panelCentral = new javax.swing.JPanel();
        jPanelPregResp = new javax.swing.JPanel();
        panelListaRespuestas1 = new eOlympics.PanelListaRespuestas();
        jPanelBotones = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanelPruebas.setName("jPanelPruebas"); // NOI18N
        jPanelPruebas.setLayout(new java.awt.BorderLayout());

        labelListado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelListado.setForeground(new java.awt.Color(0, 0, 153));
        labelListado.setText("Listado de Pruebas a realizar");
        labelListado.setName("labelListado"); // NOI18N
        jPanelPruebas.add(labelListado, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tablaPruebasARealizar1.setName("tablaPruebasARealizar1"); // NOI18N
        jScrollPane1.setViewportView(tablaPruebasARealizar1);

        jPanelPruebas.add(jScrollPane1, java.awt.BorderLayout.PAGE_END);

        add(jPanelPruebas, java.awt.BorderLayout.NORTH);

        panelCentral.setName("panelCentral"); // NOI18N
        panelCentral.setLayout(new java.awt.BorderLayout());

        jPanelPregResp.setBorder(javax.swing.BorderFactory.createTitledBorder("Preguntas/Respuestas"));
        jPanelPregResp.setName("jPanelPregResp"); // NOI18N
        jPanelPregResp.setLayout(new java.awt.BorderLayout());

        panelListaRespuestas1.setName("panelListaRespuestas1"); // NOI18N
        panelListaRespuestas1.setNumRespuestas(8);
        jPanelPregResp.add(panelListaRespuestas1, java.awt.BorderLayout.CENTER);

        panelCentral.add(jPanelPregResp, java.awt.BorderLayout.CENTER);

        jPanelBotones.setName("jPanelBotones"); // NOI18N

        jButton1.setText("Enviar");
        jButton1.setName("jButton1"); // NOI18N
        jPanelBotones.add(jButton1);

        jButton2.setText("Limpiar");
        jButton2.setName("jButton2"); // NOI18N
        jPanelBotones.add(jButton2);

        jButton3.setText("Cancelar");
        jButton3.setName("jButton3"); // NOI18N
        jPanelBotones.add(jButton3);

        panelCentral.add(jPanelBotones, java.awt.BorderLayout.SOUTH);

        add(panelCentral, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelPregResp;
    private javax.swing.JPanel jPanelPruebas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelListado;
    private javax.swing.JPanel panelCentral;
    private eOlympics.PanelListaRespuestas panelListaRespuestas1;
    private ejemplos.TablaPruebasARealizar tablaPruebasARealizar1;
    // End of variables declaration//GEN-END:variables

}
